version: '3'

services:
  web:
    container_name: eventmanager_web
    build:
      context: ./docker
    ports:
      - 80:80
    volumes:
      - ./:/var/www/app
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini